## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 935539514@qq.com #发送邮件的邮箱地址
    password:  eezqcyzrwtqjbfii  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8    
limit:
  register:
    ## 一分钟100次
    interval: 1
    count: 100  
email:
  ## 10秒钟
  code:
     expireTime: 60
